# (Test): Ping the capture endpoint with a simple GET request
GET {{host}}/ping?source=hurl&test=get
User-Agent: peeko-hurl
X-Long-Header: peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko-peeko
HTTP 200
